version: '3.9'
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080 # qbittorrent web UI
      - 6881:6881 # qbittorrent torrent port
      - 6881:6881/udp
      - 9696:9696 # prowlarr
    volumes:
      - /home/joel/homeserver:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - FIREWALL_VPN_INPUT_PORTS=36519
      - WIREGUARD_PRIVATE_KEY=ADNdyjZm22Do4TLVDQvBsmMhG1IWXSMucKyax251bkc=
      - WIREGUARD_PRESHARED_KEY=/+A/+T4BwIWhh77QjQ8GFiKKNF9YhvkbG8giwCiHSPg=
      - WIREGUARD_ADDRESSES=10.187.57.84
      - SERVER_COUNTRIES=New Zealand
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped
    networks:
      - vpn
      - media_network

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/joel/homeserver/radarr:/config
      - /media/harddrive/data/movies:/movies
      - /media/harddrive/data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - media_network

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/joel/homeserver/sonarr:/config
      - /media/harddrive/data/tv:/tv
      - /media/harddrive/data/downloads:/downloads
    ports:
      - 8988:8989
    restart: unless-stopped
    networks:
      - media_network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/joel/homeserver/qbittorrent:/config
      - /media/harddrive/data/downloads:/downloads
    restart: unless-stopped
    network_mode: service:gluetun

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /home/joel/homeserver/prowlarr:/config
    restart: unless-stopped
    network_mode: service:gluetun

networks:
  vpn:
    driver: bridge
  media_network:
    driver: bridge